one:
	@mkdir -p build
	@rustc one.rs -o build/one
	@./build/one

two:
	@mkdir -p build
	@rustc two.rs -o build/two

three:
	@mkdir -p build
	@rustc three.rs -o build/three
	@./build/three

four:
	@mkdir -p build
	@rustc four.rs -o build/four

five:
	@mkdir -p build
	@rustc five.rs -o build/five
	@./build/five

six:
	@mkdir -p build
	@rustc six.rs -o build/six
	@./build/six

clean:
	@rm -rf build
