cpp-part-one:
	@mkdir -p build
	@g++ part_one.cc -Wall -o build/cpp-part-one
	@./build/cpp-part-one

cpp-part-two:
	@mkdir -p build
	@g++ part_two.cc -Wall -o build/cpp-part-two
	@./build/cpp-part-two

rs-part-one:
	@mkdir -p build
	@rustc part_one.rs -o build/rs-part-one
	@./build/rs-part-one

rs-part-two:
	@mkdir -p build
	@rustc part_two.rs -o build/rs-part-two
	@./build/rs-part-two
