cpp-part-one:
	@mkdir -p build
	@g++ part_one.cc -Wall -o build/cpp-part-one
	@./build/cpp-part-one

cpp-part-two:
	@mkdir -p build
	@g++ part_two.cc -Wall -o build/cpp-part-two
	@./build/cpp-part-two

cpp-part-three:
	@mkdir -p build
	@g++ part_three.cc -Wall -o build/cpp-part-three
	@./build/cpp-part-three

cpp-part-four:
	@mkdir -p build
	@g++ part_four.cc -Wall -o build/cpp-part-four
	@./build/cpp-part-four

rs-part-one:
	@mkdir -p build
	@rustc part_one.rs -o build/rs-part-one

rs-part-two:
	@mkdir -p build
	@rustc part_two.rs -o build/rs-part-two
	@./build/rs-part-two

clean:
	@rm -rf build
